spring.application.name=samplepjt

# tomcat
server.port=8090

# dev tools
spring.devtools.restart.enabled=true

# thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html